FROM chromedp/headless-shell:latest

# RUN sed -i 's/deb.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list \
#     && sed -i 's/security.debian.org/mirrors.ustc.edu.cn/g' /etc/apt/sources.list

# RUN apt-get update && apt-get install -y procps

WORKDIR /app
COPY ./dist/headless  .
COPY html ./html
COPY static ./static

EXPOSE 8090

ENTRYPOINT ["/app/headless"]