FROM golang:1.26-alpine AS builder

WORKDIR /app

COPY . .

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o server main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/server .
COPY html ./html
COPY static ./static

EXPOSE 80

ENTRYPOINT ["/app/server"]